### PR TITLE
Update setting.js

### PR DESCRIPTION
**Pull request by Masteroshi430**
I'm not sure it's the only file to edit but it looks like that's the case. 😅
Remark: Multiple color pickers like the one for the accent color can also be a good solution for the user to fully customize the app interface.

### CODE REVIEW

**Comment by joaomgcd** [comment]
Thank you very much! :) Also added an "Auto (Darker" theme to go with it.

**Comment by joaomgcd** [comment]
About the multiple color pickers, do you mean to define the other theme colors like background color, etc?

**Comment by User5981** [comment]
> About the multiple color pickers, do you mean to define the other theme colors like background color, etc?
Yes something like :
                label:"Custom",
                backgroundColor:*Saved user choice*,
                backgroundColorPanel:*Saved user choice*,
                backgroundHover:*Saved user choice*,
                textColor:*Saved user choice*,
                accentColorLowlight:*Saved user choice*

(just an idea though)

**Comment by tommyent** [comment]
I had suggested this or user contributed themes that could be loaded at one point. My desktop is using a palette based on [https://github.com/jesseweed/seti-ui](https://github.com/jesseweed/seti-ui). I thought the themes might be a bit better since most people are not necessarily great with design. A that would require is loading a sheet with a bunch of CSS vars. This could also be useful from an accessibility standpoint.

**Comment by joaomgcd** [comment]
Ok, I simply made almost every color customizable :) Let me know how that works for you.

**Pull request merged**
